### ISSUE TITLE
Bug in prior for a[1]?

### ISSUE THREAD

**Issue by jeffpollock9** [milkha/Splines_in_Stan#6]
Hello,

Just wondering if there is a bug in [b_spline_penalized.stan](https://github.com/milkha/Splines_in_Stan/blob/master/b_spline_penalized.stan)? It is written in the doc that:

a_1 ~ N(0, tau)

but in the stan code:

```
a[1] = a_raw[1];
```

with `a_raw[1] ~ normal(0, 1);`. Should this be:

```
a[1] = a_raw[1] * tau;
```

Thanks!

**Comment by milkha** [comment]
Thanks for pointing this out. Actually, the code is right and the text had to be edited. We allow the first coefficient to has a N(0,1) prior, and then other coefficients have small variations with respect to previous ones.

**Comment by jeffpollock9** [comment]
@milkha many thanks!
